apiVersion: v1
kind: Service
metadata:
  name: mongodb-primary-nodeport
  namespace: scof-dev
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: mongodb-0
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30002
    name: mongodb

