apiVersion: v1
kind: Service
metadata:
  name: mongodb-external
  namespace: scof-dev
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017        # 서비스 안에서 보이는 포트
      targetPort: 27017  # 파드가 열고 있는 포트
      nodePort: 30002    # ← 여기 네가 원하는 포트