apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: scof-dev
spec:
  serviceName: mongodb-headless
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
          name: mongodb
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: scof-dev-secret
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: scof-dev-secret
              key: MONGO_INITDB_ROOT_PASSWORD
        - name: REPLICA_SET_NAME
          valueFrom:
            configMapKeyRef:
              name: scof-dev-config
              key: MONGODB_REPLICA_SET_NAME
        command:
        - mongod
        - --replSet
        - $(REPLICA_SET_NAME)
        - --keyFile
        - /etc/mongodb.key
        - --bind_ip_all
        volumeMounts:
        - name: data
          mountPath: /data/db
        - name: mongodb-key
          mountPath: /etc/mongodb.key
          subPath: mongodb.key
          readOnly: true
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - >-
              if [ -n "$MONGO_INITDB_ROOT_USERNAME" ] && [ -n "$MONGO_INITDB_ROOT_PASSWORD" ]; then
                mongosh "mongodb://$MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_PASSWORD@127.0.0.1:27017/?authSource=admin&directConnection=true" --quiet --eval 'db.adminCommand("ping")';
              else
                mongosh "mongodb://127.0.0.1:27017/?directConnection=true" --quiet --eval 'db.adminCommand("ping")';
              fi
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: mongodb-key
        secret:
          secretName: scof-dev-secret
          defaultMode: 256
          items:
          - key: MONGODB_KEY
            path: mongodb.key
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: scof-dev-sc
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
